#
# Copyright 2021 Laird Connectivity
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += imx8mp_turbosom.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o lpddr4_timing.o
endif

obj-y += ../../freescale/common/
