#! /bin/sh

set -- $(sed -nr 's,.*/dev/(mmcblk[0-9]+)p([0-9]+).*,\1 \2,p' /proc/cmdline)
mmc="${1}"
part="${2}"

read -r mmctype < /sys/block/${mmc}/device/type                             
[ "${mmctype}" != "MMC" ] || \
        /usr/bin/mount -o nosuid,nodev,noatime,noexec /dev/mmcblk2p7 /perm
