#! /bin/sh

die() {
    echo "${1}" >&2
    exit 2
}

usage() {
    echo "Usage: $0: [-m <method>] [-s <side>] [-x value] [-q] [-v] <url>"
    exit 1
}

[ $# -ge 1 ] || usage

unset o_method
unset o_side
o_quiet=true
o_restart=true

update_ok=false

while getopts m:s:x:qv name; do
    case ${name} in
    m)  o_method=${OPTARG} ;;
    s)  o_side=${OPTARG} ;;
    x)  case "${OPTARG}" in
            *r*) o_restart=false ;;
        esac ;;
    v)  o_verbose="-v"; o_quiet=false ;;
    ?)  usage ;;
    esac
done
shift $((OPTIND - 1))

url="${1}"

# determine update side
set -- $(sed -nr 's,.*/dev/(mmcblk[0-9]+)p([0-9]+).*,\1 \2,p' /proc/cmdline)
mmc="${1}"
part="${2}"

read -r mmctype < /sys/block/${mmc}/device/type                             
[ "${mmctype}" = "SD" ] && run_on_sd=true || run_on_sd=false                

if [ -z "${o_side}" ]; then
    [ "${part}" -ge 4 ] && o_side=a || o_side=b
fi

if [ -z "${o_method}" ]; then
    ${run_on_sd} && o_method=complete || o_method=full
fi

[ "${o_method}" = complete ] && o_complete=true || o_complete=false

${o_complete} && p_method=${o_method} || p_method=${o_method}-${o_side}

${o_complete} && ! ${run_on_sd} && \
    die "complete method not supported when booting from flash"

${o_quiet} && exec >/dev/null

case "${url}" in
*://*)
    if [ -x /usr/bin/curl ]; then 
        download_cmd="/usr/bin/curl -s ${url} --output -"
    elif [ -x /usr/bin/wget ]; then
        download_cmd="/usr/bin/wget -qO - ${url}"
    else
        die("Download utility not found (need curl or wget)")
    fi

    if  ${o_complete}; then
        . erase_som_nand
    fi
    ${download_cmd} | swupdate-client -e stable,${p_method} ${o_verbose} - | tee /tmp/swup
    ;;

*)
    swupdate-client -e stable,${p_method} ${o_verbose} "${url}" | tee /tmp/swup
    ;;
esac

grep -q "SWUPDATE successful" /tmp/swup && update_ok=true || update_ok=false
rm -f /tmp/swup

if ${update_ok} && ${o_restart} && ! ${run_on_sd}; then
   reboot
fi
