#!/bin/sh
# SPDX-License-Identifier: LicenseRef-Ezurio-Clause
# Copyright (C) 2025 Ezurio

if [ -r /sys/devices/soc0/soc_id ]; then
	read -r soc_id < /sys/devices/soc0/soc_id
	case "${soc_id}" in
		sama5d31)
			keyrev=$(fw_printenv -n keyrev)
			[ -z "${keyrev}" ] || keyrev="-${keyrev}"

			SWUPDATE_ARGS="${SWUPDATE_ARGS} -H wb50${keyrev}:1.0 -q stable,main-a -q stable,main-b"
			;;

		sama5d36)
			[ -r /etc/hw_rev ] && read -r HW_REV < /etc/hw_rev
			[ -n "$HW_REV" ] || HW_REV="1.0"

			ram_size=$(sed -rn 's/MemTotal:\s*([0-9]+).*/\1/p' /proc/meminfo)

			if [ "${ram_size}" -ge $((128 * 1024)) ]; then
				HW_ARGS="-H som60x2:${HW_REV}"
			else
				HW_ARGS="-H som60:${HW_REV}"
			fi

			[ -r /etc/swu_args ] && \
			read -r CUST_ARGS < /etc/swu_args

			SWUPDATE_ARGS="${SWUPDATE_ARGS} ${HW_ARGS} ${CUST_ARGS} -q stable,main-a -q stable,main-b"
			;;
	esac
fi

SWUPDATE_ARGS="${SWUPDATE_ARGS} -q stable,full-a -q stable,full-b -q stable,complete"
