#@TYPE: Machine
#@NAME: AM62XX CARBON
#@DESCRIPTION: Machine configuration for the AM62XX CARBON

require conf/machine/include/am62xx-carbon.inc
require conf/machine/include/ti-extras.inc

KERNEL_DEVICETREE_PREFIX = " \
    ti/k3-am625-carbon \
"

KERNEL_DEVICETREE123 = " \
    ti/k3-am625-carbon-dvk.dts \
    ti/k3-am625-carbon-m2.dtsi \
    ti/k3-am625-carbon-som.dtsi \
    ti/k3-am625-carbon-wifi.dtsi \
    ti/k3-am625-carbon-wifi-cc33xx.dtsi \
    ti/k3-am625-carbon-wifi-lwb-if.dtsi \
    ti/k3-am625-carbon-wifi-nx6xx.dtsi \
    ti/k3-am625-carbon-csi2-imx219.dtso \
    ti/k3-am625-carbon-csi2-ov5640.dtso \
    ti/k3-am625-carbon-lvds-hdmi-adapter.dtso \
    ti/k3-am625-carbon-m2-60.dtso \
    ti/k3-am625-carbon-m2-cc33xx.dtso \
    ti/k3-am625-carbon-m2-lwb-if.dtso \
    ti/k3-am625-carbon-m2-nx6xx.dtso \
    ti/k3-am625-carbon-rgb-hdmi-adapter.dtso \
    ti/k3-am625-carbon-rgb-lvds-adapter.dtso \
"

UBOOT_MACHINE = "carbon_am62_a53_defconfig"
