#@TYPE: Machine
#@NAME: AM62X CARBON
#@DESCRIPTION: Machine configuration for the AM62X CARBON

require conf/machine/include/am62-carbon.inc

KERNEL_DEVICETREE = " \
    ti/k3-am625-carbon-cam-a-ov5640.dtbo \
    ti/k3-am625-carbon-cam-a-ov5645.dtbo \
    ti/k3-am625-carbon-cam-a-pivariety.dtbo \
    ti/k3-am625-carbon-dvk.dtb \
    ti/k3-am625-carbon-lvds-d-10.dtbo \
    ti/k3-am625-carbon-lvds-d-7.dtbo \
    ti/k3-am625-carbon-lvds-d-hdmi.dtbo \
    ti/k3-am625-carbon-lvds-e-hdmi.dtbo \
    ti/k3-am625-carbon-m2-60-sdio-sdio.dtbo \
    ti/k3-am625-carbon-m2-60-sdio-uart.dtbo \
    ti/k3-am625-carbon-m2-lwb-if.dtbo \
    ti/k3-am625-carbon-m2-nx6xx.dtbo \
    ti/k3-am625-carbon-m2-ti3xx.dtbo \
    ti/k3-am625-carbon-rgb-hdmi.dtbo \
    ti/k3-am625-carbon-rgb-lvds-10.dtbo \
    ti/k3-am625-carbon-rgb-lvds-7.dtbo \
    ti/k3-am625-carbon-wifi-60-sdio-sdio.dtbo \
    ti/k3-am625-carbon-wifi-60-sdio-uart.dtbo \
    ti/k3-am625-carbon-wifi-60-sdio-uart-stop.dtbo \
    ti/k3-am625-carbon-wifi-lwb-if.dtbo \
    ti/k3-am625-carbon-wifi-nx6xx.dtbo \
    ti/k3-am625-carbon-wifi-ti3xx.dtbo \
    "

FIT_CONF_DEFAULT_DTB = "k3-am625-carbon-dvk.dtb"

UBOOT_MACHINE = "carbon_am62_a53_defconfig"
