#@TYPE: Machine
#@NAME: AM62XX CARBON
#@DESCRIPTION: Machine configuration for the AM62XX CARBON

require conf/machine/include/am62xx-carbon.inc
require conf/machine/include/ti-extras.inc

KERNEL_DEVICETREE = " \
    ti/k3-am625-carbon-dvk.dtb \
    ti/k3-am625-carbon-csi2-imx219.dtbo \
    ti/k3-am625-carbon-csi2-ov5640.dtbo \
    ti/k3-am625-carbon-lvds-d-hdmi-adapter.dtbo \
    ti/k3-am625-carbon-lvds-display.dtbo \
    ti/k3-am625-carbon-lvds-e-hdmi-adapter.dtbo \
    ti/k3-am625-carbon-m2-60.dtbo \
    ti/k3-am625-carbon-m2-cc33xx.dtbo \
    ti/k3-am625-carbon-m2-lwb-if.dtbo \
    ti/k3-am625-carbon-m2-nx6xx.dtbo \
    ti/k3-am625-carbon-rgb-hdmi-adapter.dtbo \
    ti/k3-am625-carbon-rgb-lvds-adapter.dtbo \
"

FIT_CONF_DEFAULT_DTB = "k3-am625-carbon-dvk.dtb"

UBOOT_MACHINE = "carbon_am62_a53_defconfig"
