#@TYPE: Machine
#@NAME: AM62XX Carbon (R5F)
#@DESCRIPTION: Machine configuration for the TI AM62xx Carbon (R5F core)

require conf/machine/include/k3r5.inc
require conf/machine/include/carbon-summitsom.inc

SYSFW_SOC = "am62x"
SYSFW_CONFIG = "carbon"
SYSFW_SUFFIX = "hs-fs"

UBOOT_MACHINE = "carbon_am62_r5_defconfig"
