#@TYPE: Machine
#@NAME: AM62LX CARBON
#@DESCRIPTION: Machine configuration for the AM62LX CARBON eMMC

require conf/machine/include/am62lxx.inc
require conf/machine/include/am62lx-carbon.inc

MACHINEOVERRIDES =. "summitsom_osm:"

MACHINE_FEATURES:remove = "nand"

KERNEL_DEVICETREE = " \
    ti/k3-am62l-carbon-dvk_emmc.dtb \
    ti/k3-am62l-carbon-dsi-a-10.dtbo \
    ti/k3-am62l-carbon-dsi-a-7.dtbo \
    ti/k3-am62l-carbon-m2-60-sdio-sdio.dtbo \
    ti/k3-am62l-carbon-m2-60-sdio-uart.dtbo \
    ti/k3-am62l-carbon-m2-ifx-sdio.dtbo \
    ti/k3-am62l-carbon-m2-nx6xx-sdio.dtbo \
    ti/k3-am62l-carbon-m2-ti3xx-sdio.dtbo \
    ti/k3-am62l-carbon-m2-usb.dtbo \
    ti/k3-am62l-carbon-wifi-ifx.dtbo \
    ti/k3-am62l-carbon-wifi-nx6xx.dtbo \
    ti/k3-am62l-carbon-wifi-ti3xx.dtbo \
    "

FIT_CONF_DEFAULT_DTB = "k3-am62l-carbon-dvk_emmc.dtb"

UBOOT_MACHINE = "carbon_am62l_emmc_defconfig"

SUMMIT_SOM_RADIO_TYPE ?= "dvk-combo"
