#@TYPE: Machine
#@NAME: AM62XX Carbon (R5F)
#@DESCRIPTION: Machine configuration for the Ezurio AM62x Carbon (R5F core)

require conf/machine/include/k3r5.inc
require conf/machine/include/k3r5-carbon.inc

UBOOT_MACHINE = "carbon_am62_r5_defconfig"
