#@TYPE: Machine
#@NAME: AM62LX CARBON
#@DESCRIPTION: Machine configuration for the AM62LX CARBON

require conf/machine/include/am62lxx.inc
require conf/machine/include/am62lx-carbon.inc

MACHINEOVERRIDES:append = ":summitsom_osm:am62lx-nand"

KERNEL_DEVICETREE = " \
    ti/k3-am62l-carbon-dvk.dtb \
    ti/k3-am62l-carbon-dsi-a-10.dtbo \
    ti/k3-am62l-carbon-dsi-a-7.dtbo \
    ti/k3-am62l-carbon-m2-60-sdio-sdio.dtbo \
    ti/k3-am62l-carbon-m2-60-sdio-uart.dtbo \
    ti/k3-am62l-carbon-m2-ifx-sdio.dtbo \
    ti/k3-am62l-carbon-m2-nx6xx-sdio.dtbo \
    ti/k3-am62l-carbon-m2-ti3xx-sdio.dtbo \
    ti/k3-am62l-carbon-m2-usb.dtbo \
    ti/k3-am62l-carbon-wifi-ifx.dtbo \
    ti/k3-am62l-carbon-wifi-nx6xx.dtbo \
    ti/k3-am62l-carbon-wifi-ti3xx.dtbo \
    "

FIT_CONF_DEFAULT_DTB = "k3-am62l-carbon-dvk.dtb"

UBOOT_MACHINE = "carbon_am62l_defconfig"

SUMMIT_SOM_RADIO_TYPE ?= "dvk-combo"
