#@TYPE: Machine
#@NAME: AM67 CARBON
#@DESCRIPTION: Machine configuration for the AM67 CARBON

require conf/machine/include/j722s.inc
require conf/machine/include/carbon-summitsom.inc

MACHINE_FEATURES += "pci"

KERNEL_DEVICETREE = " \
    ti/k3-am675-carbon-cam-a-ov5640.dtbo \
    ti/k3-am675-carbon-cam-a-ov5645.dtbo \
    ti/k3-am675-carbon-cam-a-pivariety.dtbo \
    ti/k3-am675-carbon-cam-b-ov5640.dtbo \
    ti/k3-am675-carbon-cam-b-ov5645.dtbo \
    ti/k3-am675-carbon-cam-b-pivariety.dtbo \
    ti/k3-am675-carbon-cam-c-ov5640.dtbo \
    ti/k3-am675-carbon-cam-c-ov5645.dtbo \
    ti/k3-am675-carbon-cam-c-pivariety.dtbo \
    ti/k3-am675-carbon-cam-d-ov5640.dtbo \
    ti/k3-am675-carbon-cam-d-ov5645.dtbo \
    ti/k3-am675-carbon-cam-d-pivariety.dtbo \
    ti/k3-am675-carbon-dsi-a-10.dtbo \
    ti/k3-am675-carbon-dsi-a-7.dtbo \
    ti/k3-am675-carbon-dsi-a-hdmi.dtbo \
    ti/k3-am675-carbon-dvk.dtb \
    ti/k3-am675-carbon-lvds-d-10.dtbo \
    ti/k3-am675-carbon-lvds-d-7.dtbo \
    ti/k3-am675-carbon-lvds-d-hdmi.dtbo \
    ti/k3-am675-carbon-lvds-e-10.dtbo \
    ti/k3-am675-carbon-lvds-e-7.dtbo \
    ti/k3-am675-carbon-lvds-e-hdmi.dtbo \
    ti/k3-am675-carbon-m2-60-pcie-uart.dtbo \
    ti/k3-am675-carbon-m2-60-sdio-sdio.dtbo \
    ti/k3-am675-carbon-m2-60-sdio-uart.dtbo \
    ti/k3-am675-carbon-m2-ifx-sdio.dtbo \
    ti/k3-am675-carbon-m2-ifx-pcie.dtbo \
    ti/k3-am675-carbon-m2-nx6xx-sdio.dtbo \
    ti/k3-am675-carbon-m2-ti3xx-sdio.dtbo \
    ti/k3-am675-carbon-wifi-ifx.dtbo \
    ti/k3-am675-carbon-wifi-nx6xx.dtbo \
    ti/k3-am675-carbon-wifi-ti3xx.dtbo \
    "

FIT_CONF_DEFAULT_DTB = "k3-am675-carbon-dvk.dtb"

UBOOT_MACHINE = "carbon_am67_a53_defconfig"
