#@TYPE: Machine
#@NAME: AM67 Carbon (R5F)
#@DESCRIPTION: Machine configuration for the Ezurio AM67 Carbon (R5F core)

require conf/machine/include/k3r5.inc
require conf/machine/include/carbon-summitsom.inc

SYSFW_SOC = "am67x"
SYSFW_CONFIG = "carbon"
SYSFW_SUFFIX = "hs-fs"

UBOOT_MACHINE = "carbon_am67_r5_defconfig"
