#@TYPE: Machine
#@NAME: Nitrogen SMARC i.MX8M Mini
#@SOC: i.MX8
#@DESCRIPTION: Machine configuration for Nitrogen SMARC i.MX8M Mini
#@MAINTAINER: Boris Krasnovskiy <Boris.Krasnovskiy@ezurio.com>

require conf/machine/imx8mm-nitrogen.conf

UBOOT_MACHINE = "nitrogen_imx8mm_4g_defconfig"
