#@TYPE: Machine
#@NAME: Summit SOM i.MX8M Plus
#@SOC: i.MX8
#@DESCRIPTION: Machine configuration for Summit SOM i.MX8M Plus
#@MAINTAINER: Boris Krasnovskiy <Boris.Krasnovskiy@ezurio.com>

require conf/machine/include/imx8mp-summitsom.inc

KERNEL_DEVICETREE_BASENAME = "imx8mp-summitsom"

KERNEL_DEVICETREE = " \
    freescale/imx8mp-summitsom-dvk.dtb \
    freescale/imx8mp-summitsom-hdmi.dtbo \
    freescale/imx8mp-summitsom-lvds-bridge.dtbo \
    freescale/imx8mp-summitsom-m7-rpmsg.dtbo \
    freescale/imx8mp-summitsom-mipi-bridge.dtbo \
    freescale/imx8mp-summitsom-mipi-rm67191.dtbo \
    freescale/imx8mp-summitsom-mipi-rm67199.dtbo \
    freescale/imx8mp-summitsom-wifi-pcie-uart.dtbo \
    freescale/imx8mp-summitsom-wifi-sdio-sdio.dtbo \
    freescale/imx8mp-summitsom-wifi-sdio-uart.dtbo \
    freescale/imx8mp-summitsom-wifi-sdio-uart-stop.dtbo \
    freescale/imx8mp-summitsom-wifi-sdio-uart-susp.dtbo \
    "

FIT_CONF_DEFAULT_DTB = "imx8mp-summitsom-dvk.dtb"

UBOOT_MACHINE = "summitsom_imx8mp_defconfig"
