#@TYPE: Machine
#@NAME: Nitrogen SMARC i.MX8M Mini 1GB
#@SOC: i.MX8
#@DESCRIPTION: Machine configuration for Nitrogen SMARC i.MX8M Mini 1GB
#@MAINTAINER: Boris Krasnovskiy <Boris.Krasnovskiy@ezurio.com>

require conf/machine/imx8mm-nitrogen-smarc-2g.conf

UBOOT_MACHINE = "nitrogen_imx8mm_smarc_1g_defconfig"
