#@TYPE: Machine
#@NAME: Nitrogen i.MX8M Plus 4GB
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for Nitrogen i.MX8M Plus 4GB
#@MAINTAINER: Boris Krasnovskiy <Boris.Krasnovskiy@ezurio.com>

require conf/machine/imx8mp-nitrogen-2g-r2.conf

UBOOT_MACHINE = "nitrogen_imx8mp_4g_defconfig"
