#@TYPE: Machine
#@NAME: Nitrogen SMARC i.MX8M Mini
#@SOC: i.MX8
#@DESCRIPTION: Machine configuration for Nitrogen SMARC i.MX8M Mini
#@MAINTAINER: Boris Krasnovskiy <Boris.Krasnovskiy@ezurio.com>

require conf/machine/include/imx8mm-nitrogen.inc

KERNEL_DEVICETREE_BASENAME = "nitrogen-imx8mm-smarc"

KERNEL_DEVICETREE = " \
    freescale/nitrogen-imx8mm-smarc-dvk.dtb \
    freescale/nitrogen-imx8mm-smarc-csi1-ov5640.dtbo \
    freescale/nitrogen-imx8mm-smarc-csi1-ov5645.dtbo \
    freescale/nitrogen-imx8mm-smarc-csi1-pivariety.dtbo \
    freescale/nitrogen-imx8mm-smarc-dsi0-10.dtbo \
    freescale/nitrogen-imx8mm-smarc-dsi0-7.dtbo \
    freescale/nitrogen-imx8mm-smarc-lvds0-10.dtbo \
    freescale/nitrogen-imx8mm-smarc-lvds0-7.dtbo \
    freescale/nitrogen-imx8mm-smarc-m2-60-sdio-sdio.dtbo \
    freescale/nitrogen-imx8mm-smarc-m2-60-sdio-uart.dtbo \
    freescale/nitrogen-imx8mm-smarc-m2-ifx-sdio.dtbo \
    freescale/nitrogen-imx8mm-smarc-m2-nx6xx-sdio.dtbo \
    freescale/nitrogen-imx8mm-smarc-m2-pcie.dtbo \
    freescale/nitrogen-imx8mm-smarc-m2-ti3xx-sdio.dtbo \
    freescale/nitrogen-imx8mm-smarc-mcu.dtbo \
    freescale/nitrogen-imx8mm-smarc-wifi-ifx.dtbo \
    freescale/nitrogen-imx8mm-smarc-wifi-nx6xx.dtbo \
    freescale/nitrogen-imx8mm-smarc-wifi-ti3xx.dtbo \
   "

FIT_CONF_DEFAULT_DTB = "nitrogen-imx8mm-smarc-dvk.dtb"

UBOOT_MACHINE = "nitrogen_imx8mm_defconfig"
