#@TYPE: Machine
#@NAME: Nitrogen i.MX8M Plus 2GB Rev 1
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for Nitrogen i.MX8M Plus 2GB Rev 1
#@MAINTAINER: Boris Krasnovskiy <Boris.Krasnovskiy@ezurio.com>

require conf/machine/imx8mp-nitrogen-smarc-2g-r2.conf

UBOOT_MACHINE = "nitrogen_imx8mp_2g_r1_defconfig"
