#@TYPE: Machine
#@NAME: Nitrogen i.MX93
#@SOC: i.MX93
#@DESCRIPTION: Machine configuration for Nitrogen i.MX93
#@MAINTAINER: Boris Krasnovskiy <Boris.Krasnovskiy@ezurio.com>

require conf/machine/include/imx93-nitrogen.inc

MACHINEOVERRIDES =. "summitsom_osm_m:"

KERNEL_DEVICETREE_BASENAME = "nitrogen-imx93-osm-m"

KERNEL_DEVICETREE = " \
    freescale/nitrogen-imx93-osm-m-dvk.dtb \
    freescale/nitrogen-imx93-osm-m-csi-a-ov5640.dtbo \
    freescale/nitrogen-imx93-osm-m-csi-a-ov5645.dtbo \
    freescale/nitrogen-imx93-osm-m-dsi0-10.dtbo \
    freescale/nitrogen-imx93-osm-m-dsi0-7.dtbo \
    freescale/nitrogen-imx93-osm-m-ethosu.dtbo \
    freescale/nitrogen-imx93-osm-m-lvds-d-10.dtbo \
    freescale/nitrogen-imx93-osm-m-lvds-d-7.dtbo \
    freescale/nitrogen-imx93-osm-m-lvds-d-hdmi.dtbo \
    freescale/nitrogen-imx93-osm-m-m2-60-sdio-sdio.dtbo \
    freescale/nitrogen-imx93-osm-m-m2-60-sdio-uart.dtbo \
    freescale/nitrogen-imx93-osm-m-m2-ifx-sdio.dtbo \
    freescale/nitrogen-imx93-osm-m-m2-nx6xx-sdio.dtbo \
    freescale/nitrogen-imx93-osm-m-m2-ti3xx-sdio.dtbo \
    freescale/nitrogen-imx93-osm-m-m2-usb.dtbo \
    freescale/nitrogen-imx93-osm-m-mcu.dtbo \
    freescale/nitrogen-imx93-osm-m-wifi-ifx.dtbo \
    freescale/nitrogen-imx93-osm-m-wifi-nx6xx.dtbo \
    freescale/nitrogen-imx93-osm-m-wifi-ti3xx.dtbo \
"

FIT_CONF_DEFAULT_DTB = "nitrogen-imx93-osm-m-dvk.dtb"

UBOOT_MACHINE = "nitrogen_imx93_osm_m_defconfig"

SUMMIT_SOM_RADIO_TYPE ?= "dvk-combo"
