#@TYPE: Machine
#@NAME: Nitrogen i.MX93
#@SOC: i.MX93
#@DESCRIPTION: Machine configuration for Nitrogen i.MX93
#@MAINTAINER: Boris Krasnovskiy <Boris.Krasnovskiy@ezurio.com>

require conf/machine/include/imx93-nitrogen.inc

KERNEL_DEVICETREE_BASENAME = "nitrogen-imx93-smarc"

KERNEL_DEVICETREE = " \
    freescale/nitrogen-imx93-smarc-dvk.dtb \
    freescale/nitrogen-imx93-smarc-csi0-ov5640.dtbo \
    freescale/nitrogen-imx93-smarc-csi0-ov5645.dtbo \
    freescale/nitrogen-imx93-smarc-dsi0-10.dtbo \
    freescale/nitrogen-imx93-smarc-dsi0-7.dtbo \
    freescale/nitrogen-imx93-smarc-ethosu.dtbo \
    freescale/nitrogen-imx93-smarc-lvds1-10.dtbo \
    freescale/nitrogen-imx93-smarc-lvds1-7.dtbo \
    freescale/nitrogen-imx93-smarc-m2-60-sdio-sdio.dtbo \
    freescale/nitrogen-imx93-smarc-m2-60-sdio-uart.dtbo \
    freescale/nitrogen-imx93-smarc-m2-ifx-sdio.dtbo \
    freescale/nitrogen-imx93-smarc-m2-nx6xx-sdio.dtbo \
    freescale/nitrogen-imx93-smarc-m2-ti3xx-sdio.dtbo \
    freescale/nitrogen-imx93-smarc-mcu.dtbo \
    freescale/nitrogen-imx93-smarc-spi-slave.dtbo \
    freescale/nitrogen-imx93-smarc-wifi-ifx.dtbo \
    freescale/nitrogen-imx93-smarc-wifi-nx6xx.dtbo \
    freescale/nitrogen-imx93-smarc-wifi-ti3xx.dtbo \
"

FIT_CONF_DEFAULT_DTB = "nitrogen-imx93-smarc-dvk.dtb"

UBOOT_MACHINE = "nitrogen_imx93_defconfig"

SUMMIT_SOM_RADIO_TYPE ?= "dvk-combo"
