#@TYPE: Machine
#@NAME: Nitrogen i.MX93
#@SOC: i.MX93
#@DESCRIPTION: Machine configuration for Nitrogen i.MX93
#@MAINTAINER: Boris Krasnovskiy <Boris.Krasnovskiy@ezurio.com>

require conf/machine/include/imx93-nitrogen.inc

MACHINEOVERRIDES =. "summitsom_osm_s:"

KERNEL_DEVICETREE_BASENAME = "nitrogen-imx93-osm-s"

KERNEL_DEVICETREE = " \
	freescale/nitrogen-imx93-osm-s-dvk.dtb \
	freescale/nitrogen-imx93-osm-s-m2-60-sdio-sdio.dtbo \
	freescale/nitrogen-imx93-osm-s-m2-60-sdio-uart.dtbo \
	freescale/nitrogen-imx93-osm-s-m2-ifx-sdio.dtbo \
	freescale/nitrogen-imx93-osm-s-m2-nx6xx-sdio.dtbo \
	freescale/nitrogen-imx93-osm-s-m2-ti3xx-sdio.dtbo \
	freescale/nitrogen-imx93-osm-s-wifi-ifx.dtbo \
	freescale/nitrogen-imx93-osm-s-wifi-nx6xx.dtbo \
	freescale/nitrogen-imx93-osm-s-wifi-ti3xx.dtbo \
"

FIT_CONF_DEFAULT_DTB = "nitrogen-imx93-osm-s-dvk.dtb"

UBOOT_MACHINE = "nitrogen_imx93_osm_s_defconfig"

SUMMIT_SOM_RADIO_TYPE ?= "dvk-combo"
