# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend \
    "

RFPROS_FILESHARE_AUTH ?= ""

BBFILE_COLLECTIONS += "summit-som"
BBFILE_PATTERN_summit-som = "^${LAYERDIR}/"
BBFILE_PRIORITY_summit-som = "9"

LAYERSERIES_COMPAT_summit-som = "walnascar"

SUMMIT_SOM_KEYS_DIR = "${LAYERDIR}/keys"

BBFILES_DYNAMIC += " \
    fsl-bsp-release:${LAYERDIR}/dynamic-layers/imx-bsp/recipes-*/*/*.bb \
    fsl-bsp-release:${LAYERDIR}/dynamic-layers/imx-bsp/recipes-*/*/*.bbappend \
    meta-ti-bsp:${LAYERDIR}/dynamic-layers/ti-bsp/recipes-*/*/*.bb \
    meta-ti-bsp:${LAYERDIR}/dynamic-layers/ti-bsp/recipes-*/*/*.bbappend \
    meta-summit-radio:${LAYERDIR}/dynamic-layers/summit-radio/recipes-*/*/*.bb \
    meta-summit-radio:${LAYERDIR}/dynamic-layers/summit-radio/recipes-*/*/*.bbappend \
    "

BBMASK += " \
    meta-imx-bsp/recipes-security/parsec-service \
    meta-imx-bsp/recipes-devtools/clang \
    meta-imx-bsp/recipes-core/systemd/systemd_%.bbappend \
    meta-imx-bsp/recipes-core/psplash \
    meta-imx-sdk/recipes-core/systemd \
    "

ERROR_QA:remove:summit-som = "patch-status"
