# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

RFPROS_FILESHARE_AUTH ?= ""

BBFILE_COLLECTIONS += "summit-som"
BBFILE_PATTERN_summit-som = "^${LAYERDIR}/"
BBFILE_PRIORITY_summit-som = "9"

LAYERSERIES_COMPAT_summit-som = "scarthgap"

SUMMIT_SOM_KEYS_DIR = "${LAYERDIR}/keys"

SUMMIT_SOM_LAYERDIR = "${LAYERDIR}"

BBFILES_DYNAMIC += " \
    fsl-bsp-release:${LAYERDIR}/dynamic-layers/imx-bsp/recipes-*/*/*.bb \
    fsl-bsp-release:${LAYERDIR}/dynamic-layers/imx-bsp/recipes-*/*/*.bbappend \
    meta-ti-bsp:${LAYERDIR}/dynamic-layers/ti-bsp/recipes-*/*/*.bb \
    meta-ti-bsp:${LAYERDIR}/dynamic-layers/ti-bsp/recipes-*/*/*.bbappend \
    summit-radio:${LAYERDIR}/dynamic-layers/summit-radio/recipes-*/*/*.bb \
    summit-radio:${LAYERDIR}/dynamic-layers/summit-radio/recipes-*/*/*.bbappend \
    "

BBMASK += " \
    meta-imx-bsp/recipes-core/psplash \
    "
