#! /bin/sh

FDT_FILE=$(fw_printenv -n fdt_file)

case "$1" in
  mfg)
    FDT_FILE=${FDT_FILE/dvk/mfg}
    ;;

  dvk)
    FDT_FILE=${FDT_FILE/mfg/dvk}
    ;;
esac

fw_setenv fdt_file ${FDT_FILE}
reboot