#
# Copyright 2021 Laird Connectivity
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += imx8mp_summitsom.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o

obj-y += lpddr4_timing_all.o

endif

obj-y += ../../freescale/common/
