require conf/distro/poky.conf

DISTRO = "summitsom-rescue"
DISTRO_NAME = "Summit SOM SD card Rescue"

INIT_MANAGER = "sysvinit"

DISTRO_FEATURES_DEFAULTS = "lto"

DISTRO_FEATURES = "\
    usrmerge \
    largefile \
    xattr \
    ipv4 \
    ipv6 \
    usbgadget \
    "

VIRTUAL-RUNTIME_init_manager = "busybox"

NO_RECOMMENDATIONS = "1"

GLIBC_GENERATE_LOCALES = " "
IMAGE_LINGUAS = " "

SELECTED_OPTIMIZATION = "-Os -pipe ${DEBUG_LEVELFLAG}"

PACKAGE_CLASSES:summitsom ?= "package_ipk"
