require conf/distro/poky.conf

DISTRO = "summitsom-wbx3"
DISTRO_NAME = "Summit SOM SD card WBx3"

INIT_MANAGER = "sysvinit"

DISTRO_FEATURES_DEFAULTS = ""

DISTRO_FEATURES = "\
    usrmerge \
    largefile \
    xattr \
    ipv4 \
    ipv6 \
    usbgadget \
    "

VIRTUAL-RUNTIME_init_manager = "busybox"

NO_RECOMMENDATIONS = "1"

GLIBC_GENERATE_LOCALES ?= " "
IMAGE_LINGUAS ?= " "

PACKAGE_CLASSES:summitsom ?= "package_ipk"

PACKAGECONFIG:remove:pn-modemmanager = "vala"
