require summitsom-wayland.conf
include conf/distro/b2qt.conf

DISTRO = "summitsom-b2qt-webengine"
DISTRO_NAME = "Summit SOM b2qt WebEngine"

DISTROOVERRIDES .= ":summit-b2qt"

DISTRO_FEATURES:remove = "virtualization"

DEPLOY_CONF_NAME:am62xx = "Carbon AM62"
DEPLOY_CONF_NAME:j722s = "Carbon AM67"

QBSP_IMAGE_CONTENT += "\
    ${IMAGE_BASENAME}-${MACHINE}.wic.bz2 \
    ${IMAGE_BASENAME}-${MACHINE}.conf \
    ${IMAGE_BASENAME}-${MACHINE}.info \
    "

DISTRO_FEATURES:remove = "ld-is-gold"

PREFERRED_PROVIDER_virtual/egl_am62xx = "ti-img-rogue-umlibs"
PREFERRED_PROVIDER_virtual/libgles1_am62xx = "ti-img-rogue-umlibs"
PREFERRED_PROVIDER_virtual/libgles2_am62xx = "ti-img-rogue-umlibs"
PREFERRED_PROVIDER_virtual/libgbm_am62xx = "ti-img-rogue-umlibs"
PREFERRED_PROVIDER_virtual/egl_j722s = "ti-img-rogue-umlibs"
PREFERRED_PROVIDER_virtual/libgles1_j722s = "ti-img-rogue-umlibs"
PREFERRED_PROVIDER_virtual/libgles2_j722s = "ti-img-rogue-umlibs"
PREFERRED_PROVIDER_virtual/libgbm_j722s = "ti-img-rogue-umlibs"

BBMASK += "\
    meta-boot2qt/meta-boot2qt-distro/recipes-containers/containerd/containerd-opencontainers_%.bbappend \
    meta-boot2qt/meta-boot2qt-distro/recipes-containers/docker/docker-moby_%.bbappend \
    meta-boot2qt/meta-boot2qt-distro/recipes-devtools/mingw-w64/nativesdk-mingw-w64-headers_%.bbappend \
    meta-boot2qt/meta-boot2qt-distro/recipes-devtools/mingw-w64/nativesdk-mingw-w64-runtime_%.bbappend \
    meta-boot2qt/meta-boot2qt-distro/recipes-core/systemd/systemd_%.bbappend \
    "
