require conf/distro/poky.conf

INIT_MANAGER = "systemd"

DISTRO = "summitsom-cmd"
DISTRO_NAME = "Summit SOM Command Line"

DISTRO_FEATURES_DEFAULTS = "multilib"

DISTRO_FEATURES = "\
    usrmerge \
    largefile \
    xattr \
    ipv4 \
    ipv6 \
    systemd \
    alsa \
    usbhost \
    usbgadget \
    ${@bb.utils.contains('BBFILE_COLLECTIONS', 'summit-radio', 'wifi bluetooth', '', d)} \
    "

VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""
VIRTUAL-RUNTIME_base-utils-hwclock = "util-linux-hwclock"

NO_RECOMMENDATIONS = "1"

GLIBC_GENERATE_LOCALES ?= "en_US.UTF-8"
IMAGE_LINGUAS ?= "en-us"

PACKAGE_CLASSES:summitsom ?= "package_ipk"

PACKAGECONFIG:remove:pn-modemmanager = "vala"

FILESYSTEM_PERMS_TABLES:remove = "files/fs-perms-volatile-log.txt"
