require summitsom-wbx3.conf

DISTRO = "summitsom-wbx3-initramfs"
DISTRO_NAME = "Summit SOM WBx3 Initramfs"

DISTRO_FEATURES:append = " summitsom-wbx3-initramfs"

DISTROOVERRIDES .= ":summitsom-wbx3-initramfs"
