require conf/distro/poky.conf

DISTRO = "summitsom-wbx3"
DISTRO_NAME = "Summit SOM WBx3"

DISTRO_FEATURES = "\
    usrmerge \
    largefile \
    xattr \
    ipv4 \
    ipv6 \
    usbhost \
    usbgadget \
    sysvinit \
    summitsom-wbx3 \
    "

DISTRO_FEATURES_BACKFILL_CONSIDERED += "pulseaudio gobject-introspection-data ldconfig"

DISTROOVERRIDES .= ":summitsom-wbx3"

VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""
VIRTUAL-RUNTIME_base-utils-hwclock = "util-linux-hwclock"
VIRTUAL-RUNTIME_init_manager = "sysvinit"
VIRTUAL-RUNTIME_initscripts = "initscripts"
VIRTUAL-RUNTIME_login_manager = ""
VIRTUAL-RUNTIME_dev_manager = "eudev"

# Prevent sysvinit-inittab from adding serial/VT getty entries;
# the image recipe writes its own autologin entry instead.
SERIAL_CONSOLES = ""
USE_VT = "0"

#NO_RECOMMENDATIONS = "1"

GLIBC_GENERATE_LOCALES ?= "en_US.UTF-8"
IMAGE_LINGUAS ?= "en-us"

PACKAGE_CLASSES:summitsom ?= "package_ipk"

PACKAGECONFIG:remove:pn-modemmanager = "vala"

FILESYSTEM_PERMS_TABLES:remove = "files/fs-perms-volatile-log.txt"
