require conf/distro/poky.conf

POKY_INIT_MANAGER = "systemd"

DISTRO = "summitsom-cmd"
DISTRO_NAME = "Summit SOM Command Line"

DISTRO_FEATURES = "usrmerge largefile xattr ipv4 ipv6 systemd wifi bluetooth"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "gobject-introspection-data"

VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""
VIRTUAL-RUNTIME_base-utils-hwclock = "util-linux-hwclock"

#NO_RECOMMENDATIONS = "1"

GLIBC_GENERATE_LOCALES ?= "en_US.UTF-8"
IMAGE_LINGUAS ?= "en-us"

PACKAGE_CLASSES = "package_ipk"

PACKAGECONFIG:remove:pn-modemmanager = "vala"
