
include summit-platform-version.inc

SUMMIT_PLATFORM_VERSION ?= "master"

OVERRIDES =. "${@ "summit-pv:" if d.getVar('SUMMIT_PLATFORM_VERSION', False).startswith('LRD-REL-') else ''}"

PV ?= "${SUMMIT_PLATFORM_VERSION}+git"
PV:summit-pv = "${@ d.getVar('SUMMIT_PLATFORM_VERSION').split('-')[2]}"

SUMMIT_PLATFORM_BRANCH ?= "branch=${SUMMIT_PLATFORM_VERSION}"
SUMMIT_PLATFORM_BRANCH:summit-pv = "nobranch=1"

SRCREV ?= "${AUTOREV}"
SRCREV:summit-pv = "${SUMMIT_PLATFORM_VERSION}"

SUMMIT_EXTERNAL_GIT_URI ?= "git://github.com/Ezurio"
SUMMIT_EXTERNAL_GIT_PROTOCOL ?= "https"
SUMMIT_EXTERNAL_GIT_SUFFIX ?= "protocol=${SUMMIT_EXTERNAL_GIT_PROTOCOL};${SUMMIT_PLATFORM_BRANCH}"

SUMMIT_INTERNAL_GIT_URI ?= "git://github.com/rfpros"
SUMMIT_INTERNAL_GIT_PROTOCOL ?= "https"
SUMMIT_INTERNAL_GIT_SUFFIX ?= "protocol=${SUMMIT_INTERNAL_GIT_PROTOCOL};${SUMMIT_PLATFORM_BRANCH}"
