OS_RELEASE_FIELDS += "BUILD_ID"

SUMMIT_VERSION ?= "0.0.0.0"
SUMMIT_RELEASE_STRING ?= "Summit Linux development build 0.0.0.0"

ID = "${IMAGE_BASENAME}"
NAME = "Summit Linux"
VERSION = "${SUMMIT_RELEASE_STRING}"
VERSION_ID = "${SUMMIT_VERSION}"
PRETTY_NAME = "${SUMMIT_RELEASE_STRING}"
