OS_RELEASE_FIELDS += "BUILD_ID"

LRD_VERSION ?= "0.0.0.0"
LAIRD_RELEASE_STRING ?= "Summit Linux development build 0.0.0.0"

ID = "${IMAGE_BASENAME}"
NAME = "Summit Linux"
VERSION = "${LAIRD_RELEASE_STRING}"
VERSION_ID = "${LRD_VERSION}"
PRETTY_NAME = "${LAIRD_RELEASE_STRING}"
