#!/bin/bash
# -*- mode: shell-script; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# Copyright (C) 2012, 2013, 2016 O.S. Systems Software LTDA.
# Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Add options for the script
# Copyright (C) 2013 Freescale Semiconductor, Inc.

CWD=${PWD}
PROGNAME="setup-environment"

usage()
{
    cat << EOF
Usage: [MACHINE=<machine>] [DISTRO=<distro>] . ${PROGNAME} [-i] [-r] [-v] [-a] [-h] <build-dir>
    <machine>    machine name
    <distro>     distro name
    <build-dir>  build directory

    Optional parameters:
    * [-i]: Internal build
    * [-r]: Add Radio DVK to setup
    * [-a]: Development desktop setup (enable all)
    * [-v]: Add Vigiles check to setup
    * [-h]: help

The first usage is for creating a new build directory. In this case, the
script creates the build directory <build-dir>, configures it for the
specified <machine> and <distro>, and prepares the calling shell for running
bitbake on the build directory.

The second usage is for using an existing build directory. In this case,
the script prepares the calling shell for running bitbake on the build
directory <build-dir>. The build directory configuration is unchanged.

Supported machines:
$(basename -as .conf sources/meta-summit-som/conf/machine/imx*.conf | sed '/^\*/d; s/^/\t/g')

Supported distros:
$(basename -as .conf sources/meta-summit-som/conf/distro/*.conf | sed '/^\*/d; s/^/\t/g')

Examples:

- To create a new Yocto build directory:
  $ MACHINE=imx8mp-summitsom DISTRO=summitsom-wayland . ${PROGNAME} build

- To use an existing Yocto build directory:
  $ . ${PROGNAME} build
EOF
}

clean_up()
{
   unset EULA REPLY
   unset CWD ARGS PROGNAME
   unset MACHINE DISTRO OEROOT
   unset build_dir_setup_enabled setup_radio setup_summit setup_vigiles
}

setup_radio=false
setup_summit=false
setup_vigiles=false

ARGS=$(getopt -o "hirva" -l "help," --name ${PROGNAME} -- "$@" )
# Print the usage menu if invalid options are specified
if [ $? != 0 ] || [ $# -lt 1 ]; then
   usage && clean_up
   return 1
fi

eval set -- "${ARGS}"
while true;
do
    case ${1} in
        -h|--help)
           usage
           clean_up
           return 0
           ;;
        -r)
           setup_radio=true
           ;;
        -a)
           setup_radio=true
           setup_summit=true
           setup_vigiles=true
           ;;
        -i)
           setup_summit=true
           ;;
        -v)
           setup_vigiles=true
           ;;
        --)
           shift
           break
           ;;
    esac
    shift
done

if [ "$(id -u)" -eq 0 ]; then
    echo "ERROR: do not use the BSP as root. Exiting..."
    clean_up
    return 1
fi

[ -e "${1}/conf/local.conf" ] && build_dir_setup_enabled=false ||
    build_dir_setup_enabled=true

[ -z "${FSL_EULA_FILE}" ] && FSL_EULA_FILE=${CWD}/sources/meta-imx/LICENSE.txt
if [ ! -e "${FSL_EULA_FILE}" ]; then
    echo -e "ERROR: EULA not found at ${FSL_EULA_FILE}."
    clean_up
    return 1
fi

OEROOT=${PWD}/sources/openembedded-core

if [ -n "${RFPROS_FILESHARE_USER}" ] && [ -n "${RFPROS_FILESHARE_PASS}" ]; then
    export RFPROS_FILESHARE_AUTH="${RFPROS_FILESHARE_USER}:${RFPROS_FILESHARE_PASS}@"
    BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} RFPROS_FILESHARE_AUTH"
fi

[ -n "${BR2_DL_DIR}" ] && DL_DIR="${BR2_DL_DIR}" || DL_DIR="${HOME}/.br2_dl_dir"
export DL_DIR
BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} DL_DIR SSTATE_DIR VIGILES_KEY_FILE"

BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} SIG_DATA_PATH SECURE_BOOT"

if [ -n "${BB_HASHSERVE_DB_DIR}" ]; then
    BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} BB_HASHSERVE_DB_DIR"
else
    export BB_SIGNATURE_HANDLER="OEBasicHash"
    BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} BB_SIGNATURE_HANDLER"
fi

if [ -n "${VERSION}" ]; then
    export IMAGE_VERSION_SUFFIX="-${VERSION}"
    export SUMMIT_VERSION="${VERSION}"
    BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} IMAGE_VERSION_SUFFIX SUMMIT_VERSION SUMMIT_RELEASE_STRING"
fi

# shellcheck source=/dev/null
TEMPLATECONF=${TEMPLATECONF:-${CWD}/sources/meta-summit-som/conf/templates/nxp} \
    . "${OEROOT}/oe-init-build-env" "${CWD}/${1}"

if ${build_dir_setup_enabled}; then
    # Change settings according environment
    [ -n "${MACHINE}" ] && sed -e "s,MACHINE ??=.*,MACHINE ??= '${MACHINE}',g" -i conf/local.conf
    [ -n "${DISTRO}"  ] && sed -e "s,DISTRO ?=.*,DISTRO ?= '${DISTRO}',g" -i conf/local.conf

    {
        ${setup_summit} || printf '# '
        echo 'OVERRIDES .= ":summit-internal"'

        ${setup_vigiles} || printf '# '
        echo 'INHERIT += "vigiles"'
    } >> conf/local.conf

    {
        ${setup_radio} || printf '# '
        # shellcheck disable=SC2016
        echo 'BBLAYERS += "${BSPDIR}/sources/meta-summit-rdvk"'
    } >> conf/bblayers.conf
fi

# Handle EULA setting
EULA_ACCEPTED=

# EULA has been accepted already (ACCEPT_FSL_EULA is set in local.conf)
if grep -q '^\s*ACCEPT_FSL_EULA\s*=\s*["'\'']..*["'\'']' conf/local.conf; then
    EULA_ACCEPTED=1
fi

if [ -z "${EULA_ACCEPTED}" ] && [ -n "${EULA}" ]; then
    # The FSL EULA is not set as accepted in local.conf, but the EULA
    # variable is set in the environment, so we just configure
    # ACCEPT_FSL_EULA in local.conf according to $EULA.
    echo "ACCEPT_FSL_EULA = \"${EULA}\"" >> conf/local.conf
elif [ -n "${EULA_ACCEPTED}" ]; then
    # The FSL EULA has been accepted once, so ACCEPT_FSL_EULA is set
    # in local.conf.  No need to do anything.
    :
else
    # THE FSL EULA is not set as accepted in local.conf, and EULA is
    # not set in the environment, so we need to ask user if he/she
    # accepts the FSL EULA:
    cat <<EOF

Some BSPs depend on libraries and packages which are covered by NXP's
End User License Agreement (EULA). To have the right to use these binaries in
your images, you need to read and accept the following...

EOF

    sleep 4

    more -d "${FSL_EULA_FILE}"
    echo
    REPLY=
    while [ -z "${REPLY}" ]; do
        printf "Do you accept the EULA you just read? (y/n) "
        read -r REPLY
        case "${REPLY}" in
            y|Y)
            echo "EULA has been accepted."
            echo "ACCEPT_FSL_EULA = \"1\"" >> conf/local.conf
            ;;
            n|N)
            echo "EULA has not been accepted."
            ;;
            *)
            REPLY=
            ;;
        esac
    done
fi

clean_up
