#! /bin/sh

case "${1}" in
  pcie-uart|sdio-uart|sdio-sdio|sdio-uart-stop|sdio-uart-susp)
    ;;

  *)
    echo "usage: set-radio-mode [sdio-uart | sdio-sdio | pcie-uart | sdio-uart-stop | sdio-uart-susp ]"
    exit 1
    ;;
esac

FDT_FILE=$(fw_printenv -n conf)

prefix=$(echo "${FDT_FILE}" | sed -n 's,\([^-]\+\-[^-]\+\-[^-]\+\-[^-]\+\).*,\1,p')

case "$FDT_FILE" in
  *m7-rpmsg*)
    suffix="-m7-rpmsg"
    ;;
  *)
    suffix=""
    ;;
esac

FDT_FILEN="${prefix}-${1}${suffix}.dtb"

[ -n "${prefix}" ] && [ "${FDT_FILE}" != "${FDT_FILEN}" ] || exit

fw_setenv conf ${FDT_FILEN}

pwd=${PWD}
cd /lib/firmware/lrdmwl/

case "${1}" in
 sdio-sdio)
   ln -sf 88W8997_SOM8MP_sdio_sdio_* 88W8997_sdio.bin
   ;;

 sdio-uart*)
   ln -sf 88W8997_SOM8MP_sdio_uart_* 88W8997_sdio.bin
   ;;
esac

cd ${pwd}

systemctl reboot
